version: '1.0.{build}'
build_cloud: azure
image: preloaded-vm

branches:
  only:
  - debug_withmt

init:
    # Good practise, because Windows line endings are different from Unix/Linux ones
    - cmd: git config --global core.autocrlf true

install:
    # Nothing to install

before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    - cmd: nuget restore     
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
    # Not sure whats happening here

after_build:
    # Nothing to do after build 

test_script:
    # try auto mode
    
on_finish :
    # any cleanup in here

deploy: off