version: '1.0.{build}'
image: Visual Studio 2017

branches:
  only:
  - appveyor
  - saml-integration-tests

init:
    # Good practise, because Windows line endings are different from Unix/Linux ones
    - cmd: git config --global core.autocrlf true

install:
    # Nothing to install

before_build:
    # Display .NET Core version
    - cmd: dotnet --version
    - cmd: nuget restore 

build_script:
    # Not sure whats happening here

after_build:
    # Nothing to do after build 

artifacts:
    - path: '\Saml\bin\Debug\Saml.dll'
      name: Saml Assembly
      type: WebDeployPackage

test_script:
    # try auto mode
    
on_finish :
    # any cleanup in here

deploy: off