version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build:
    executor: win/win/vs2019
    steps:
      - checkout
      - run:
          name: MSBuild
          environment:
          command: |
            msbuild "Saml.sln" /p:Configuration=Release -t:restore,build -p:RestorePackagesConfig=true
            if ($LastExitCode -ne 0) { $lastexitcode; throw "Build Error" }

workflows:
  build_and_test:
    jobs:
      - build