version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build_and_test:
    executor: win/server-2019
    steps:
      - checkout
      - run:
          name: MSBuild
          command: |
            msbuild "Saml.sln" /p:Configuration=Release -t:restore,build -p:RestorePackagesConfig=true
      - run:
          name: MSTest
          environment:
            VSTEST: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/Extensions/TestPlatform/vstest.console.exe'
          command: |
            & $env:VSTEST "saml.Test\saml.Test\bin\Release\Saml.Test.dll" /Logger:trx /ResultsDirectory:UnitTestResults
            # "Saml.Integration\bin\Release\Saml.Integration.dll"  Integration Tests are broken becuase SAML login page has changed. The account does not exist either.
      - store_test_results:
          path: UnitTestResults

workflows:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - master