version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build_and_test:
    executor: win/server-2019
    steps:
      - checkout
      - run:
          name: MSBuild
          command: |
            msbuild "Saml.sln" /p:Configuration=Release -t:restore,build -p:RestorePackagesConfig=true
      - run:
          name: MSTest
          command: |
            mstest "Saml.Integration\bin\Release\Saml.Integration.dll" "saml.Test\saml.Test\bin\Release\Saml.Test.dll"

workflows:
  build_and_test:
    jobs:
      - build_and_test